### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by mileung**

### CODE REVIEW

**Comment by kevr** [comment]
I can resolve this for you; what is your meeting times?

**Comment by kevr** [comment]
Assumed that you wanted to update from what was already there, removed the `<p>shit</p>` element.

Edit: Please don't commit foul language or otherwise unprofessional details to the club's Github repositories, these could be used in the future for students to showcase what they have done etc.

**Comment by kevr** [comment]
At another look... looks like I removed the wrong area? I'll join Slack to discuss this.

**Comment by mileung** [comment]
Haha, this was just for a git/github example yesterday. Meetings are every other Friday 2 - 3 PM. Next meeting is in two weeks.

**Comment by kevr** [comment]
Ah, I see. Okay.

**Pull request merged**
